#!/usr/bin/env node
/**
 * Wrap the compiled browser half in DSH's client module shell.
 *
 * The web client evaluates every `client.js` as a **classic script** — several
 * of them arrive in one `??`-combined response — so an ESM bundle fails with
 * "Cannot use import statement outside a module" and takes the whole batch of
 * plugins down with it. Every working client plugin therefore ships the same
 * shell: `window.__ModuleLoader__.load({ id, factory: (require) => … })`, with
 * the module body compiled to CJS so `require("react")` resolves through the
 * loader's platform table.
 *
 * Run: node scripts/wrap-client.mjs   (after tsdown; part of `pnpm build`)
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const target = join(root, 'lib', 'client.js')
const { name } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const MARK = '// Generated by scripts/wrap-client.mjs'
const OPEN = [
  `${MARK} — do not edit by hand.`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
].join('\n')
const TAG = '    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });'
const PROLOGUE = `${OPEN}\n`
const EPILOGUE = '    return module.exports;\n  },\n});\n'

/**
 * Recover the bare bundle from an already-wrapped file, so running the wrapper
 * twice is a no-op instead of nesting shells.
 * @param text - current file contents.
 * @returns the unwrapped bundle body.
 */
function unwrap(text) {
  if (!text.startsWith(MARK)) return text
  const start = text.indexOf(PROLOGUE)
  const end = text.lastIndexOf(EPILOGUE)
  if (start !== 0 || end < 0) throw new Error('lib/client.js looks hand-edited; rebuild before wrapping')
  const inner = text.slice(PROLOGUE.length, end)
  return inner.startsWith(`${TAG}\n`) ? inner.slice(TAG.length + 1) : inner
}

const body = unwrap(readFileSync(target, 'utf8'))

// `exports.foo = …` is CJS and fine; a statement-level `import`/`export` is not.
if (/^\s*(?:import|export)\s/m.test(body)) {
  throw new Error(
    'lib/client.js still contains ESM syntax — the client build must emit CJS ' +
      "(tsdown format: ['cjs']) before the DSH ModuleLoader shell is applied",
  )
}

// The `require` handed to a factory is synchronous and resolves against the
// platform seed table plus registered factories — anything else throws on the
// spot while the plugin materializes. Only the shell's frozen baseline may
// appear; the names are `PLATFORM_MODULES` in the DSH checkout verbatim.
const BASELINE = new Set([
  'react',
  'react/jsx-runtime',
  'react-dom',
  'react-dom/client',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-store',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-ui-primitives',
  '@deepseek-ai/dsh-client-ui-dockkit',
])
const requests = [...new Set([...body.matchAll(/\brequire\(\s*["']([^"']+)["']\s*\)/g)].map((m) => m[1]))]
const unresolved = requests.filter((specifier) => !BASELINE.has(specifier))

if (unresolved.length > 0) {
  throw new Error(
    `lib/client.js requests modules the DSH module table cannot supply: ${unresolved.join(', ')}. ` +
      'Inline them, or move the shared runtime code into a baseline module.',
  )
}

writeFileSync(
  target,
  PROLOGUE +
    '\n' +
    (body.includes('Symbol.toStringTag') ? '' : `${TAG}\n`) +
    body.trimEnd() +
    '\n' +
    EPILOGUE,
)

console.log(
  `wrapped lib/client.js in the DSH ModuleLoader shell (id ${name}, ` +
    `externals: ${requests.join(', ') || 'none'})`,
)
